version: "3.8"

services:
  backend:
    build: ./backend
    image: my-backend:latest
    container_name: backend
    ports:
      - "3000:3000"
    env_file:
      - ./backend/.env
    depends_on:
      - db  # <-- backend waits for db to start

  frontend:
    build: ./frontend
    image: my-frontend:latest
    container_name: frontend
    ports:
      - "5173:5173"

  db:   # <-- this is your MySQL service
    image: mysql:8
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: smart_workspace
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
